name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Railway link (if IDs provided)
        if: ${{ secrets.RAILWAY_PROJECT_ID != '' || secrets.RAILWAY_SERVICE_ID != '' }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: |
          set -e
          if [ -n "${RAILWAY_PROJECT_ID}" ]; then
            railway link --project ${RAILWAY_PROJECT_ID}
          fi
          if [ -n "${RAILWAY_SERVICE_ID}" ]; then
            railway link --service ${RAILWAY_SERVICE_ID}
          fi

      - name: Railway deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
        run: |
          if [ -n "${RAILWAY_SERVICE_NAME}" ]; then
            railway up --service "${RAILWAY_SERVICE_NAME}"
          else
            railway up
          fi
